# Config file for VoteReward by LDX.
#
# Official VoteReward Server List Directory:
# http://votereward.mcpe.me/?p=lists
#
# Config Variables:
#   {USERNAME} ... The username of the player who voted. ....... Commands and message.
#   {NICKNAME} ... The display name of the player who voted. ... Commands and message.
#   {X} .......... The X coordinate of the player. ............. Commands only.
#   {Y} .......... The Y coordinate of the player. ............. Commands only.
#   {Y1} ......... The Y coordinate of the player plus 1. ...... Commands only.
#   {Z} .......... The Z coordinate of the player. ............. Commands only.

# EssentialsPE style color codes can be used in the message and commands.

# Message to broadcast to the server when a player votes.
Message: "&0[&eKP&0] &b{USERNAME} &5has voted and received: &61 Mythic Crate, &e2 Common Crate, &63 Vote crate! &l&bAND 60K&a$ &r&fIn Game!"

# List of items to give players when they vote. Format: ID:Damage:Amount
Items:
  - "322:0:10"
  - "466:0:2"
  - "276:0:1"

# List of commands to execute when a player votes.
Commands:
  - "key Mythic {USERNAME} 1"
  - "key Common {USERNAME} 2"
  - "key Vote {USERNAME} 3"
  - "givemoney {USERNAME} 60000"
  - "tell {USERNAME} &6We appreciate &eyour support.  don't forget &6to vote again tomorrow &e:D"
  
